# Generated by Django 3.2.6 on 2021-08-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loginfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginfo',
            name='user',
        ),
        migrations.AddField(
            model_name='loginfo',
            name='login',
            field=models.CharField(default='login', max_length=255),
        ),
    ]
